import { Link } from "expo-router";
import { ArrowRight, Camera, Shield, Sparkles, Trophy } from "lucide-react-native";
import { Pressable, SafeAreaView, ScrollView, StyleSheet, Text, View } from "react-native";

const GOLD = "#F5C542";

export default function Landing() {
  return <SafeAreaView style={styles.safe}><ScrollView contentContainerStyle={styles.container}>
    <View style={styles.header}><View style={styles.brand}><Sparkles color={GOLD} size={24} /><Text style={styles.brandText}>Heapsal</Text></View><Link href="/(tabs)/dashboard" asChild><Pressable><Text style={styles.login}>Log In</Text></Pressable></Link></View>
    <View style={styles.hero}><View style={styles.pill}><Sparkles color={GOLD} size={13} /><Text style={styles.pillText}>Your VIP backstage pass to your best self</Text></View><Text style={styles.title}>Unlock Your{"\n"}<Text style={styles.gold}>True Potential</Text></Text><Text style={styles.subtitle}>Upload a photo for a world-class AI analysis of your skin, style, and aesthetics. Build habits that transform you.</Text><Link href="/(tabs)/dashboard" asChild><Pressable style={styles.primary}><Text style={styles.primaryText}>Start Your Heapsal</Text><ArrowRight color="#17130A" size={21} /></Pressable></Link><Text style={styles.note}>Takes less than 2 minutes. Free to start.</Text></View>
    <View style={styles.features}><Feature icon={<Camera color={GOLD} size={21} />} title="AI Aesthetic Analysis" text="Deep analysis of skin, hair, facial structure & style." /><Feature icon={<Shield color={GOLD} size={21} />} title="Daily Wellness Routine" text="Personalized actionable steps based on your results." /><Feature icon={<Trophy color={GOLD} size={21} />} title="Gamified Transformation" text="Track streaks, earn XP, and unlock achievements." /></View>
  </ScrollView></SafeAreaView>;
}
function Feature({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <View style={styles.feature}><View style={styles.icon}>{icon}</View><View style={{ flex: 1 }}><Text style={styles.featureTitle}>{title}</Text><Text style={styles.featureText}>{text}</Text></View></View>; }
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: "#0D0D0D" }, container: { flexGrow: 1, padding: 24 }, header: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" }, brand: { flexDirection: "row", alignItems: "center", gap: 8 }, brandText: { color: "#FFF", fontSize: 20, fontWeight: "800" }, login: { color: "#FFF", fontSize: 14 }, hero: { alignItems: "center", paddingTop: 76 }, pill: { flexDirection: "row", alignItems: "center", gap: 7, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 18, backgroundColor: "#1B1912", borderWidth: 1, borderColor: "#3A321D" }, pillText: { color: GOLD, fontSize: 11 }, title: { color: "#FFF", fontSize: 43, lineHeight: 50, fontWeight: "800", textAlign: "center", marginTop: 25 }, gold: { color: GOLD }, subtitle: { color: "#A5A5A5", fontSize: 16, lineHeight: 25, textAlign: "center", marginTop: 22, maxWidth: 350 }, primary: { marginTop: 32, width: "100%", height: 58, borderRadius: 18, backgroundColor: GOLD, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 10 }, primaryText: { color: "#17130A", fontSize: 17, fontWeight: "800" }, note: { color: "#777", fontSize: 12, marginTop: 12 }, features: { gap: 12, marginTop: 58 }, feature: { flexDirection: "row", gap: 14, padding: 18, borderRadius: 20, backgroundColor: "#171717", borderWidth: 1, borderColor: "#262626" }, icon: { width: 42, height: 42, borderRadius: 21, backgroundColor: "#292213", alignItems: "center", justifyContent: "center" }, featureTitle: { color: "#FFF", fontSize: 15, fontWeight: "700", marginBottom: 5 }, featureText: { color: "#999", fontSize: 13, lineHeight: 19 } });
